# Generated by Django 5.2.4 on 2026-06-23 02:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brightness_product_color_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_name', models.CharField(blank=True, max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('naver_product_id', models.CharField(blank=True, max_length=100)),
                ('is_representative', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_no', models.CharField(blank=True, max_length=40)),
                ('option_name', models.CharField(blank=True, max_length=200)),
                ('option_key', models.CharField(max_length=220)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('color_family', models.CharField(choices=[('PINK', '핑크'), ('ROSE', '로즈'), ('CORAL', '코랄'), ('RED', '레드'), ('BERRY', '베리'), ('LAVENDER', '라벤더'), ('BEIGE', '베이지'), ('BROWN', '브라운'), ('GRAY', '그레이'), ('IVORY', '아이보리'), ('ETC', '기타')], default='ETC', max_length=20)),
                ('analyzed_tone_tag', models.CharField(blank=True, db_index=True, max_length=80)),
                ('hex_code', models.CharField(blank=True, max_length=20)),
                ('rgb_r', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('rgb_g', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('rgb_b', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('brightness', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('saturation', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coolness', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('warmth', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('depth', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('softness', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contrast', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product', 'option_no', 'option_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionToneScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_tone', models.CharField(db_index=True, max_length=80)),
                ('match_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(choices=[('BEST', 'BEST'), ('GOOD', 'GOOD'), ('OK', 'OK'), ('CAUTION', 'CAUTION')], default='CAUTION', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_score', 'option_id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='representative_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_key__isnull', False)), fields=('canonical_key',), name='unique_product_canonical_key'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.productoption'),
        ),
        migrations.AddField(
            model_name='productoptiontonescore',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tone_scores', to='products.productoption'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'option_key'), name='unique_product_option_key'),
        ),
        migrations.AddConstraint(
            model_name='productoptiontonescore',
            constraint=models.UniqueConstraint(fields=('option', 'target_tone'), name='unique_option_target_tone_score'),
        ),
    ]
