# Generated by Django 5.2.4 on 2026-06-23 13:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productoffer_productoption_productoptiontonescore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=300)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('LIP', 'LIP'),
                            ('EYE', 'EYE'),
                            ('CHEEK', 'CHEEK'),
                            ('BASE', 'BASE'),
                            ('LENS', 'LENS'),
                            ('ETC', 'ETC'),
                        ],
                        default='ETC',
                        max_length=20,
                    ),
                ),
                ('uploaded_image', models.ImageField(upload_to='products/color-analysis/')),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product_image_analyses',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ProductImageAnalysisOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('hex_code', models.CharField(blank=True, max_length=20)),
                (
                    'color_source',
                    models.CharField(
                        choices=[
                            ('IMAGE_EXTRACTED', 'Image extracted'),
                            ('AI_ESTIMATED', 'AI estimated'),
                            ('USER_EDITED', 'User edited'),
                            ('PENDING', 'Pending'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                ('confidence', models.FloatField(blank=True, null=True)),
                (
                    'chart_x',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'chart_y',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'brightness',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'saturation',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'warmth',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'coolness',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'depth',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'softness',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'contrast',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'match_score',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'grade',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('BEST', 'BEST'),
                            ('GOOD', 'GOOD'),
                            ('CAUTION', 'CAUTION'),
                            ('PENDING', 'PENDING'),
                        ],
                        max_length=20,
                    ),
                ),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'analysis',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='options',
                        to='products.productimageanalysis',
                    ),
                ),
            ],
            options={'ordering': ['id']},
        ),
    ]
