# Generated by Django 5.2.4 on 2026-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productimageanalysis_productimageanalysisoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimageanalysis",
            name="category",
            field=models.CharField(
                choices=[
                    ("LIP", "립"),
                    ("EYE", "아이"),
                    ("CHEEK", "치크"),
                    ("BASE", "베이스"),
                    ("LENS", "렌즈"),
                    ("ETC", "기타"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
    ]
