# Generated by Django 5.2.4 on 2026-06-16 08:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
                (
                    "base_temperature",
                    models.CharField(
                        choices=[("warm", "웜(warm)"), ("cool", "쿨(cool)")],
                        max_length=5,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "봄(spring)"),
                            ("summer", "여름(summer)"),
                            ("fall", "가을(fall)"),
                            ("winter", "겨울(winter)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("BRIGHT", "브라이트(Bright)"),
                            ("LIGHT", "라이트(Light)"),
                            ("MUTE", "뮤트(Mute)"),
                            ("DEEP", "딥(Deep)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="퍼스널컬러에 대한 짧은 설명"),
                ),
                (
                    "temperature_degree",
                    models.IntegerField(
                        help_text="온도감 (0:Warm ~ 100:Cool)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "brightness_degree",
                    models.IntegerField(
                        help_text="명도 (0:Low ~ 100:High)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "saturation_degree",
                    models.IntegerField(
                        help_text="채도 (0:Low ~ 100:High)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "turbidity_degree",
                    models.IntegerField(
                        help_text="쳥량함(0) 탁함(0)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "glossiness_degree",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "contrast_degree",
                    models.IntegerField(
                        help_text="대비감 (0:Low Contrast ~ 100:High Contrast)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "best_pccs",
                    models.JSONField(
                        default=list, help_text="베스트 PCCS 톤 코드 목록"
                    ),
                ),
                (
                    "sub_pccs",
                    models.JSONField(
                        blank=True, default=list, help_text="서브 PCCS 톤 코드 목록"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColorRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REP", "대표 컬러(Representative)"),
                            ("BEST", "베스트 컬러(best)"),
                            ("WORST", "워스트 컬러(Worst)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "makeup_part",
                    models.CharField(
                        choices=[
                            ("LIP", "립(Lip)"),
                            ("BASE", "베이스(파운데이션, 블러셔, 쉐딩)"),
                            ("EYE", "아이(섀도우, 라이너, 마스카라 등)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "color_name",
                    models.CharField(
                        help_text="색상명 (예: 페일 핑크, 체리 레드)", max_length=50
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        help_text="색상 Hex Code (예: #FFC0CB)", max_length=7
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="예: 애교살 포인트용으로 추천",
                        max_length=200,
                    ),
                ),
                (
                    "personal_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_recommendation",
                        to="diagnosis.personalcolor",
                    ),
                ),
            ],
        ),
    ]
