# Generated by Django 5.2.4 on 2026-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0002_diagnosisresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisresult",
            name="generated_makeup_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="diagnosis/generated/"
            ),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="uploaded_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="diagnosis/originals/"
            ),
        ),
    ]
