# Generated by Django 5.2.4 on 2026-06-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0003_diagnosisresult_generated_makeup_image_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisresult",
            name="diagnosed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="english_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="image_features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="korean_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="personal_color_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="radar_chart",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="skin_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="style_guide",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="DiagnosisColorPalette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("best", "Best"),
                            ("neutral", "Neutral"),
                            ("accent", "Accent"),
                            ("worst", "Worst"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("hex", models.CharField(max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_palettes",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diagnosis", "group", "order"),
                        name="unique_palette_group_order",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisMakeoverStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makeover_styles",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diagnosis", "key"), name="unique_makeover_style_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisRecommendedLens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=80)),
                ("product_name", models.CharField(max_length=120)),
                ("color", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_lenses",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diagnosis", "order"),
                        name="unique_recommended_lens_order",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisRecommendedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("category_name", models.CharField(max_length=80)),
                ("tone_label", models.CharField(max_length=120)),
                ("brand", models.CharField(max_length=80)),
                ("product_name", models.CharField(max_length=120)),
                ("shade", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("product_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_products",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosis_recommendations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diagnosis", "category"),
                        name="unique_recommended_product_category",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisRepresentativeColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("hex", models.CharField(max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative_colors",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diagnosis", "order"),
                        name="unique_representative_color_order",
                    )
                ],
            },
        ),
    ]
