# Generated by Codex on 2026-06-23

from django.db import migrations, models
from django.db.models import Q


def assign_latest_primary(apps, schema_editor):
    DiagnosisResult = apps.get_model('diagnosis', 'DiagnosisResult')
    user_ids = (
        DiagnosisResult.objects.order_by()
        .values_list('user_id', flat=True)
        .distinct()
    )
    for user_id in user_ids:
        latest = (
            DiagnosisResult.objects.filter(user_id=user_id)
            .order_by('-created_at', '-id')
            .first()
        )
        if latest:
            DiagnosisResult.objects.filter(pk=latest.pk).update(is_primary=True)


def clear_primary_flags(apps, schema_editor):
    DiagnosisResult = apps.get_model('diagnosis', 'DiagnosisResult')
    DiagnosisResult.objects.update(is_primary=False)


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_makeover_style_status_and_job_style_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(assign_latest_primary, clear_primary_flags),
        migrations.AddConstraint(
            model_name='diagnosisresult',
            constraint=models.UniqueConstraint(
                condition=Q(is_primary=True),
                fields=('user',),
                name='unique_primary_diagnosis_per_user',
            ),
        ),
    ]
