# Generated by Django 5.2.4 on 2026-06-23 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('products', '0003_productoffer_productoption_productoptiontonescore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedproductoption',
            name='product_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_users', to='products.productoption'),
        ),
    ]
