# Generated by Django 5.2.4 on 2026-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("LIFE_ITEM", "인생템 공유"),
                    ("COLOR_REVIEW", "발색 리뷰"),
                    ("QUESTION", "질문"),
                    ("PRODUCT_RECOMMENDATION", "제품 추천"),
                    ("ROUTINE", "메이크업 루틴"),
                    ("FREE", "자유"),
                ],
                default="FREE",
                max_length=30,
            ),
        ),
    ]
